[book]
authors = ["Chen-Pang He"]
language = "zh-TW"
src = "src"
title = "BTU Dutch Doubleton"

[output.html]
additional-css = ["style.css"]
git-repository-url = "https://github.com/jdh8/btu-dutch-doubleton"
site-url = "https://jdh8.github.io/btu-dutch-doubleton/"
smart-punctuation = true

[preprocessor.yapp]
